### PR TITLE
Add Dutch Translation

### PR DESCRIPTION
**Pull request by Sindarin27**
In the spirit of Hacktober, I decided to translate your mod. This translation contains all translation strings for Dutch players to play this mod :D

If you approve this PR, please add the label `hacktoberfest-accepted` when doing so. Thank you!

### CODE REVIEW

**Comment by Globox1997** [comment]
Haven't planned to add it to the hacktober fest..

**Comment by Sindarin27** [comment]
No matter, you can have the pull request either way because I like the mod, whether you add the label or not. It was simply that hacktoberfest inspired me to do this, and I hope you'll add the label to recognise this.

**Comment by Globox1997** [comment]
I appreciate the translation even if I think playing mc in english just helps a little bit to remember some english words :)
If I'm honest, a translation pr is imo not a real "quality" pr for a repo but of course everybody has his/her own opinion about it. In no way do I want to undervalue the work you have invested but I hope you understand what I mean

**Comment by Sindarin27** [comment]
Sure thing, I totally understand! The main reason I'm translating mods is because I have a little sister I like to play games with, who has no English skills at all. The difficulty of translation varies a lot from project to project, and I've already translated tougher mods out there. I just hope this translation will make it into the game, hacktoberfest is a side quest :P

**Comment by Globox1997** [comment]
Of course the difficulty varies a lot :) So as I said, I appreciate it ;)

**Pull request merged**
