### PR TITLE
1.18 full translation into Russian adventurez-1.4.5

### PR DESCRIPTION
**Pull request by Shelbikk**
[AdventureZ.zip](https://github.com/Globox1997/AdventureZ/files/7708974/AdventureZ.zip)

I'm a complete newbie on githab ._.

### CODE REVIEW

**Comment by Globox1997** [comment]
hey Shelbikk, this PR contains only old commits, not your translation

**Comment by Shelbikk** [comment]
Только что скачал AdventureZ 1.4.5 и там в переводе ru_ru 110 строк
В моём, новом переводе 183 строки.

I just downloaded AdventureZ 1.4.5 and there are 110 lines in the translation ru_ru
In my new translation there are 183 lines.

110 old vs 183 new.

**Comment by Globox1997** [comment]
this PR wants to push in the 1.17 branch...
It should include only the lang file update

**Comment by Globox1997** [comment]
Your pull request doesn't contain your translation. However I added it with [https://github.com/Globox1997/AdventureZ/commit/17c31eee985dd1c9e0a70ba866ba285ddf0db5ab](https://github.com/Globox1997/AdventureZ/commit/17c31eee985dd1c9e0a70ba866ba285ddf0db5ab)

**Pull request closed without merging**
